"""A weak-field field equation for rope gravity, from a stated flux assumption.

Context. The rope gravity sector previously MATCHED the weak-field metric to
isotropic Schwarzschild by hand (GRV-001, Modeled): the conformal factor
psi = 1 + r_s/(4r) was asserted, not generated. This benchmark records a modest
UPGRADE -- a field equation that generates that psi -- while being explicit that
it rests on one assumption and is intrinsically weak-field-only.

The assumption (stated, independently motivated, NOT derived from strand
mechanics): a mass sources a conserved, additive "conditioning flux" in the rope
network -- the direct gravitational analogue of the rope Gauss law already used
for EM charge. Two masses condition twice as much; the conditioning flux is
neither created nor destroyed in empty space.

Given only that assumption plus spherical symmetry, the 1/r conformal factor is
FORCED (not assumed): flux(r) * 4 pi r^2 = k * M_enclosed gives |F| ~ 1/r^2 and
hence psi - 1 ~ 1/r. Equivalently the field obeys the Poisson equation
    laplacian(psi) = -k rho .
This benchmark verifies (1) a numerical Poisson solve with a point source yields
psi ~ 1/r (the Schwarzschild conformal form), and (2) the spherical-shell flux
argument gives the inverse-square field without assuming it.

HONEST SCOPE -- this is why the claim is Conjecture, not Derived:
  * The flux assumption is reasonable and consistent with the EM Gauss law, but
    is NOT derived from strand-level rope dynamics; why mass sources it, and the
    value of the coupling (Newton's G), are inputs.
  * Poisson is LINEAR. Real gravity is nonlinear (gravity gravitates). This
    approach builds in linearity and therefore CANNOT extend to the strong field,
    gravitational waves, or cosmology -- it is structurally weak-field-only.
So this upgrades gravity from "metric matched by hand" to "weak-field metric
generated by a field equation, given one stated assumption" -- a modest, clearly
bounded improvement, not a derivation of general relativity. Registered as
GRV-003 (Conjecture).
"""
import numpy as np


def shell_flux_gives_inverse_square():
    """Gauss + spherical symmetry: flux(r)*4 pi r^2 = k M => |F| ~ 1/r^2.
    Verify the field strength scales as 1/r^2 across radii for fixed enclosed source."""
    kM = 1.0
    radii = np.array([1.0, 2.0, 4.0, 8.0])
    F = kM / (4 * np.pi * radii**2)
    # check F * r^2 is constant (inverse-square)
    return np.allclose(F * radii**2, F[0] * radii[0]**2)


def poisson_point_source_gives_inverse_r(N=64, L=8.0, k=1.0):
    """Solve laplacian(psi) = -k rho for a point source via FFT; check psi ~ 1/r."""
    dx = L / N
    x = np.linspace(-L / 2, L / 2, N)
    c = N // 2
    rho = np.zeros((N, N, N))
    rho[c, c, c] = 1.0 / dx**3
    rho_k = np.fft.fftn(-k * rho)
    kx = 2 * np.pi * np.fft.fftfreq(N, d=dx)
    KX, KY, KZ = np.meshgrid(kx, kx, kx, indexing="ij")
    K2 = KX**2 + KY**2 + KZ**2
    K2[0, 0, 0] = 1.0
    psi_k = rho_k / (-K2)
    psi_k[0, 0, 0] = 0.0
    psi = np.real(np.fft.ifftn(psi_k))
    r = np.abs(x - x[c])
    line = psi[c:, c, c]
    rr = r[c:]
    m = (rr > dx) & (rr < L / 3)
    corr = np.corrcoef(1.0 / rr[m], line[m])[0, 1]
    return corr


def test():
    assert shell_flux_gives_inverse_square(), "flux+symmetry should force inverse-square"
    corr = poisson_point_source_gives_inverse_r()
    assert corr > 0.99, f"Poisson point source should give psi~1/r (corr={corr:.3f})"
    print("shell-flux argument -> inverse-square field (1/r^2): PASS")
    print(f"Poisson point-source solve -> psi ~ 1/r: correlation {corr:.4f}")
    print("PASS: weak-field metric is GENERATED by laplacian(psi) = -k rho,")
    print("      GIVEN the (stated, undeived) assumption that mass sources a")
    print("      conserved conditioning flux. Weak-field-only; linear; not GR.")


if __name__ == "__main__":
    test()
